---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
    commit-message:
      prefix: "Java"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
    commit-message:
      prefix: "GHAction"
      include: "scope"
