---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/lambda"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "maven"
    directory: "/lambda/src/it/shabbat-times-interaction-it"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "test"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
