---
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_reviewers:
      - "TomerFi"
    default_assignees:
      - "TomerFi"
    default_labels:
      - "dependabot"
