---
name: Alexa Shabbat Times Skill

on:
  push:
    branch: master
  pull_request:
    branch: master

jobs:
  run-maven-goals:
    runs-on: ubuntu-latest
    steps:

    - name: Source checkout
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    #- name: Download maven repository
    #  uses: actions/download-artifact@v1
    #  with:
    #    name: mvnrepo

    - name: Check source files License header
      run: mvn license:check -B -ff

    - name: Validate json files
      run: mvn yaml-json-validator:validate -B -ff

    - name: Test, compile and verify JaCoCo metrics
      run: mvn verify -B -ff

    - name: Checkstyle checker
      run: mvn checkstyle:check -B -ff

    - name: PMD checker
      run: mvn pmd:check -B -ff

    - name: CPD checker
      run: mvn pmd:cpd-check -B -ff

    - name: SpotBugs checker
      run: mvn spotbugs:check -B -ff

    - name: Create javadoc files
      run: mvn javadoc:javadoc -B -ff

    #- name: Upload maven repository
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: mvnrepo
    #    path: /home/runner/.m2/repository

    - name: SonarCloud scan and report
      run: mvn sonar:sonar -B -ff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
