---
name: Build

on:
  push:
    branch: master
  pull_request:
    branch: master

jobs:

  build-validate-and-persist:
    runs-on: ubuntu-latest
    steps:

    - name: Source checkout
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up aws cli
      uses: chrislennon/action-aws-cli@v1.1

    - name: Get persistance from S3 Bucket
      shell: bash
      run: |
        aws s3 cp s3://shabbat-times/wfpersistence/ . --recursive
        tar -xzf mvnrepo.tar.gz -C /
        tar -xzf sonarcache.tar.gz -C /
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Check source files License header
      run: mvn license:check -B -ff

    - name: Validate testing json files
      run: mvn yaml-json-validator:validate -B -ff

    - name: Test, compile, package, and verify
      run: mvn verify -B -ff

    - name: Checkstyle checker
      run: mvn checkstyle:check -B -ff

    - name: PMD checker
      run: mvn pmd:check -B -ff

    - name: CPD checker
      run: mvn pmd:cpd-check -B -ff

    - name: SpotBugs checker
      run: mvn spotbugs:check -B -ff

    - name: Create javadoc files
      run: mvn javadoc:javadoc -B -ff

    - name: SonarCloud scan and report
      run: mvn sonar:sonar -B -ff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Persist to S3 Bucket
      shell: bash
      run: |
        tar -czfr mvnrepo.tar.gz /home/runner/.m2/repository
        tar -czfr sonarcache.tar.gz /home/runner/.sonar/cache
        aws s3 cp . s3://shabbat-times/wfpersistence --recursive --exclude "*" --include "*.tar.gz"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
