---
name: Rebase

on:
  issue_comment:
    types: created

jobs:
  rebase-command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/rebase')
    steps:
    - name: Source checkout
      uses: actions/checkout@v1
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
